tap "ahmetb/kubectx", "https://github.com/ahmetb/kubectx.git"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"
tap "boz/repo"
tap "dtan4/dtan4"

brew "aspell"
brew "bash-completion"
brew "blackbox"
brew "pcre"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "editorconfig"
brew "openssl"
brew "elixir"
brew "git"
brew "glide"
brew "pkg-config"
brew "hadolint"
brew "httpie"
brew "hugo"
brew "jq"
brew "kubernetes-cli"
brew "kops"
brew "kubectx", args: ["with-short-names"]
brew "kubernetes-helm"
brew "libev"
brew "libevent"
brew "lua"
brew "mas"
brew "mongodb"
brew "node"
brew "opencv"
brew "pgcli"
brew "portaudio"
brew "postgresql"
brew "redis", restart_service: true
brew "shellcheck"
brew "shpotify"
brew "tree"
brew "vim"
brew "vips", args: ["with-imagemagick", "with-openexr", "with-openslide", "without-graphicsmagick"]
brew "watch"
brew "wget"
brew "wrk"
brew "yarn", args: ["without-node"]
brew "zsh-syntax-highlighting"
brew "boz/repo/kail"
brew "dtan4/dtan4/k8sec"

cask "gitify"
